# Generated by Django 5.1.3 on 2024-11-27 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_movimiento_codigo_alter_movimiento_bodega_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='inventario.bodega'),
        ),
    ]
