# Generated by Django 5.1.3 on 2024-11-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_producto_bodega'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientodetalle',
            options={},
        ),
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
