# Generated by Django 5.1.3 on 2024-11-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_movimientodetalle_options_producto_cantidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientodetalle',
            options={'ordering': ['movimiento', 'producto']},
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
